name: Slither Analysis

on: [push]

jobs:
  analyze:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Run Slither
        env:
          RPC_ROPSTEN: ${{ secrets.RPC_ROPSTEN }}
          PRIVATE_KEY_ROPSTEN: ${{ secrets.PRIVATE_KEY_ROPSTEN }}
        uses: crytic/slither-action@v0.1.1
        continue-on-error: true
        id: slither
        with:
          node-version: 16
          sarif: results.sarif
